package vn.com.lifesup.hackathon.security;

public interface AuthorityConstant {
    String DSNV_READ = "DSNV_READ";
    String DSNV_CREATE = "DSNV_CREATE";
    String DSNV_UPDATE = "DSNV_UPDATE";
    String DSNV_DELETE = "DSNV_DELETE";
    String DSPB_READ = "DSPB_READ";
    String DSPB_CREATE = "DSPB_CREATE";
    String DSPB_UPDATE = "DSPB_UPDATE";
    String DSPB_DELETE = "DSPB_DELETE";
    String DSVT_READ = "DSVT_READ";
    String DSVT_CREATE = "DSVT_CREATE";
    String DSVT_UPDATE = "DSVT_UPDATE";
    String DSVT_DELETE = "DSVT_DELETE";
    String DSCD_READ = "DSCD_READ";
    String DSCD_CREATE = "DSCD_CREATE";
    String DSCD_UPDATE = "DSCD_UPDATE";
    String DSCD_DELETE = "DSCD_DELETE";
    String DSDT_READ = "DSDT_READ";
    String DSDT_CREATE = "DSDT_CREATE";
    String DSDT_UPDATE = "DSDT_UPDATE";
    String DSDT_DELETE = "DSDT_DELETE";
    String DSDA_READ = "DSDA_READ";
    String DSDA_CREATE = "DSDA_CREATE";
    String DSDA_UPDATE = "DSDA_UPDATE";
    String DSDA_DELETE = "DSDA_DELETE";
    String DSKPI_READ = "DSKPI_READ";
    String DSKPI_CREATE = "DSKPI_CREATE";
    String DSKPI_UPDATE = "DSKPI_UPDATE";
    String DSKPI_DELETE = "DSKPI_DELETE";
    String DSD_READ = "DSD_READ";
    String DSD_CREATE = "DSD_CREATE";
    String DSD_UPDATE = "DSD_UPDATE";
    String DSD_DELETE = "DSD_DELETE";
    String DSCC_READ = "DSCC_READ";
    String DSCC_CREATE = "DSCC_CREATE";
    String DSCC_UPDATE = "DSCC_UPDATE";
    String DSCC_DELETE = "DSCC_DELETE";
    String DSKN_READ = "DSKN_READ";
    String DSKN_CREATE = "DSKN_CREATE";
    String DSKN_UPDATE = "DSKN_UPDATE";
    String DSKN_DELETE = "DSKN_DELETE";


    String DSTV_CREATE = "DSTV_CREATE";
    String DSTV_UPDATE = "DSTV_UPDATE";
    String DSTV_DELETE = "DSTV_DELETE";
    String DSTV_READ = "DSTV_READ";

    String PHAN_QUYEN_CREATE = "PHAN_QUYEN_CREATE";

    String PHAN_QUYEN_UPDATE = "PHAN_QUYEN_UPDATE";

    String PHAN_QUYEN_DELETE = "PHAN_QUYEN_DELETE";

    String PHAN_QUYEN_READ = "PHAN_QUYEN_READ";

    String CONTRACT_CREATE = "CONTRACT_CREATE";
    String CONTRACT_UPDATE = "CONTRACT_UPDATE";
    String CONTRACT_READ = "CONTRACT_READ";
    String CONTRACT_DELETE = "CONTRACT_DELETE";

    String PROJECT_ROLE_CREATE = "PROJECT_ROLE_CREATE";
    String PROJECT_ROLE_UPDATE = "PROJECT_ROLE_UPDATE";
    String PROJECT_ROLE_READ = "PROJECT_ROLE_READ";
    String PROJECT_ROLE_DELETE = "PROJECT_ROLE_DELETE";

    String HR_DOCUMENT_CREATE = "HR_DOCUMENT_CREATE";
    String HR_DOCUMENT_UPDATE = "HR_DOCUMENT_UPDATE";
    String HR_DOCUMENT_READ = "HR_DOCUMENT_READ";
    String HR_DOCUMENT_DELETE = "HR_DOCUMENT_DELETE";
    String SALARY_CREATE = "SALARY_CREATE";
    String SALARY_UPDATE = "SALARY_UPDATE";
    String SALARY_READ = "SALARY_READ";
    String REPORT_CONFIG_READ = "REPORT_CONFIG_READ";
    String REPORT_CONFIG_CREATE = "REPORT_CONFIG_CREATE";
    String REPORT_CONFIG_UPDATE = "REPORT_CONFIG_UPDATE";
    String REPORT_CONFIG_DELETE = "REPORT_CONFIG_DELETE";
}
